# Book settings
title: Pages of Machine Learning
author: JustGlowing
logo: ml_pages_logo.png

html:
    extra_navbar: |
        <div>
            <a href="https://twitter.com/JustGlowing?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @JustGlowing</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

        </div>
